import { Geist, Geist_Mono } from "next/font/google";
import styles from "./layout.module.css";
import Image from "next/image";
import utilsStyles from "./styles/utils.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <header className={styles.header}>
            <Image className={utilsStyles.borderCircle}
              src="/imgs/profile.png"
              width={50}
              height={50}
              alt="Profile"
            ></Image>
            <h1 className={utilsStyles.heading2Xl}>Shin Code</h1>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
